Feature/tui method bodies
hold12/CDIO_del1 pull request #5
Opened 2017-02-16 21:04 UTC by KasperLeiszner

2017-02-16 23:16 UTC, algorythm requested changes
Meget fint, men jeg synes der er lidt at arbejde med endnu. Jeg tror at der er nogle ting som vil give problemer :)

2017-02-16 23:16 UTC, awo-dev commented on src/dto/User.java
> +    private ArrayList<String> roles;
Dette skal være en `List`. Du kan ikke definere den som `ArrayList` siden `ArrayList` vist nok er abstract.

2017-02-16 23:16 UTC, awo-dev commented on src/dto/User.java
> +    public User(int userId, String userName, String initials, ArrayList<String> roles, String cpr, String password) {
Det samme gælder her.
Man definerer den som:
`List<String> roles = new ArrayList<String>();`

2017-02-16 23:16 UTC, awo-dev commented on src/dto/User.java
> +    public User(int userId, String userName, String initials, ArrayList<String> roles, String cpr, String password) {
Dvs. første `List`, næste `ArrayList`.

2017-02-16 23:16 UTC, awo-dev commented on src/dto/User.java
> +    public ArrayList<String> getRoles() {
Igen, `List`

2017-02-16 23:16 UTC, awo-dev commented on src/ui/TUI.java
> +    private Scanner scanner = new Scanner(System.in);
Hvis vi laver `Scanner`-objektet her, så bare nøjes med `private Scanner scanner;` her, og så initialisér den i constructeren.

2017-02-16 23:16 UTC, awo-dev commented on src/ui/TUI.java
> +            System.out.println(user.toString());
Fint for nu, men jeg tænker at vi med siden gør det lidt tydeligere hvad der sker, men lidt mere beskrivende tekst.

2017-02-16 23:16 UTC, awo-dev commented on src/ui/TUI.java
> +    public String getUserInput()
Eftersom vi har denne metode, er det måske lidt ligegyldige at have `Scanner`-objektet class-wide? Måske er det bare mig

2017-02-16 23:16 UTC, awo-dev commented on src/ui/TUI.java
> +        System.out.print("User Roles \n" +
Dette er også fint for nu, men vi kommer nok til at have en tabel med roller. I det tilfælde, så skal vi tage en liste som argument, som indeholder alle de tilgængelige roller i programmet.

2017-02-16 23:16 UTC, awo-dev commented on src/ui/TUI.java
> +    private ArrayList<String> defineRoles()
Meget fint at have de her `defineX`-metoder, men jeg tænker vi nok bør have det i en klasse for sig selv?

2017-02-16 23:16 UTC, awo-dev commented on src/ui/TUI.java
> +    public void listUsers(ArrayList<User> listOfUser)
Her tror jeg nok det er muligt at have den abstrakte klasse, det åbner vist også op for flere typer `ArrayList`'s.

2017-02-20 12:04 UTC, awo-dev commented
Pull changes in IntelliJ (conflicts)

2017-02-20 13:31 UTC, freyahelstrup commented on src/ui/TUI.java
> +                    "4 - Exit");
Password should also be editable - right?

2017-02-20 13:37 UTC, freyahelstrup commented on src/ui/TUI.java
> +    private String defineUsername()
Is this a part of the UI's responsibility?

2017-02-20 13:38 UTC, freyahelstrup commented on src/ui/TUI.java
> +                user.getCpr());
How about we just use the user's toString method?

2017-02-20 13:40 UTC, KasperLeiszner commented on src/ui/TUI.java
> +    private String defineUsername()
Næææh egentlig ikke, flytter det nok til UIController

2017-02-20 13:41 UTC, KasperLeiszner commented on src/ui/TUI.java
> +                    "4 - Exit");
Tjooo, det skal det jo nok, men skal sikkert også flyttes til UIController

2017-02-20 13:42 UTC, KasperLeiszner commented on src/ui/TUI.java
> +    public String getUserInput()
Det kan du have ret i, hvad ville en løsning være. Uden at oprette et objekt hvergang metoden kaldes.

2017-02-20 13:42 UTC, KasperLeiszner commented on src/ui/TUI.java
> +            System.out.println(user.toString());
Enig

2017-02-20 13:42 UTC, KasperLeiszner commented on src/ui/TUI.java
> +    private Scanner scanner = new Scanner(System.in);
Er gjort ;)

2017-02-20 13:49 UTC, algorythm requested changes

2017-02-20 13:49 UTC, awo-dev commented on src/ui/TUI.java
> +                user.getCpr());
I think that too

2017-02-20 13:49 UTC, awo-dev commented on src/ui/TUI.java
> +    private String defineUsername()
Some of it is. 
The rules of how the username is supposed to be (min length, max length) is definitely **not** `UI`'s responsibility, however the `defineUsername` **is** supposed to be here (just not the rules). I guess...

2017-02-20 13:49 UTC, awo-dev commented on src/ui/TUI.java
> +    private String defineUsername()
@KasperLeiszner Det er jeg ikke sikker på er en god idé.

2017-02-20 13:49 UTC, awo-dev commented on src/ui/TUI.java
> +                    "4 - Exit");
Ikke en god idé at have den i `UIController`

2017-02-20 13:49 UTC, awo-dev commented on src/ui/TUI.java
> +    public String getUserInput()
Ved nærmere eftertanke, har jeg besluttet, at jeg nok tager fejl :)

2017-02-20 14:01 UTC, freyahelstrup commented on src/ui/UI.java
> +    User createUser();
Hvorfor er removeUser fjernet?

2017-02-20 15:03 UTC, freyahelstrup commented on src/ui/TUI.java
> +        roles.add(getUserInput("Enter roles"));
Hvordan kan man tilføje flere roller her? Lige nu er det kun muligt at indtaste én rolle, så vidt jeg kan se.

2017-02-20 15:04 UTC, freyahelstrup commented on src/ui/TUI.java
> +        roles.add(getUserInput("Enter roles"));
Hvordan kan man tilføje flere roller her? Lige nu er det kun muligt at indtaste én rolle, så vidt jeg kan se.

2017-02-20 15:06 UTC, KasperLeiszner commented on src/ui/TUI.java
> +        roles.add(getUserInput("Enter roles"));
Til at starte med nej ;)

2017-02-20 15:06 UTC, freyahelstrup commented on src/ui/TUI.java
> +        userName = getUserInput("Enter username");
Brugeren skal også kunne indtaste userId

2017-02-20 15:07 UTC, freyahelstrup commented on src/ui/TUI.java
> +        String[] optionList = {"Username", "Initials", "Roles", "Exit"};
Password skal tilføjes

2017-02-21 16:57 UTC, merged